services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: manager
    ports:
      - "5439:5432"
    volumes:
      - db-data:/var/lib/postgresql
  admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admir@321
    ports:
      - "8083:80"
    volumes:
      - admin-data:/var/lib/pgadmin
volumes:
  db-data:
  admin-data: